### PR TITLE
Build for MAC ARM; Upgrade to 2.0.6

### PR DESCRIPTION
**Pull request by baconpaul**
This fixes the FreeSurface package to build for Mac ARM. To update for Mac ARM in the VCV Rack library, if you would like to

1. Merge this change into your rack 2 branch
2. Go to https://github.com/VCVRack/library/issues/697 and post the new version number (2.0.6) and git hash (whatever the hash is post merge)

Hope this is helpful!

Thanks

### CODE REVIEW

**Comment by baconpaul** [comment]
Hi! Just cleaning up my GitHub. I'm assuming this repo is no longer monitored and the project is abandoned, but if not, wondering if you want to merge this? I'll close it next week if I don't hear.

Thanks!

**Comment by baconpaul** [comment]
Hi.

I'm going to close this pull request unmerged. 

If you do end up reviving these modules, I'm happy to help you re-apply it.

**Comment by freesurfacemodules** [comment]
Thanks for your help on this. Apologies for taking so long to address it. I have updated the build for Mac ARM

**Comment by baconpaul** [comment]
Oh cool!!

**Pull request closed without merging**
